### ISSUE TITLE
Hapi doesn't work on node 16. We need to update filecoin dependencies (ipfs?) that use it

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#1333]

**Comment by jarretmoses** [comment]
I've had an issue (not sure if it's related) due to node 16 and `µWS` with an error. If this requires a separate issue let me know.

Stack trace

```js
Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_darwin_x64_93.node'
    at /Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3677678
    at Object.71596 (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3677773)
    at __webpack_require__ (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3802718)
    at Object.72697 (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3669061)
    at __webpack_require__ (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3802718)
    at Object.63668 (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3666692)
    at __webpack_require__ (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3802718)
    at Object.3312 (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3761499)
    at __webpack_require__ (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3802718)
    at Object.75567 (/Users/jarretmoses/Learn/Blockchain/ConsensysBootcamp/filecoin-example/node_modules/ganache/dist/cli/ganache.min.js:3:3763138)
```

**Comment by phoward-tbpm** [comment]
running into this issue as well on the pet-shop-tutorial.  What do I need to update?  Newb.

**Comment by phoward-tbpm** [comment]
This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_win32_ia32_102.node'
Falling back to a NodeJS implementation; performance may be degraded.


Using network 'development'.


Compiling your contracts...
===========================
> Compiling .\contracts\Adoption.sol
> Compiling .\contracts\Migrations.sol
> Artifacts written to C:\Users\PETERH~1\AppData\Local\Temp\test--50728-plMmSh0X5wNl
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang
