### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by JMiddey** [ConsenSys-archive/ganache#1776]
I have been having trouble with ganache-cli and have not been able to use the ganache-cli command, I have played around with it by uninstalling, reinstalling and updating packages now when I use the ganache-cli command i get this:
joe@Joes-MacBook-Pro web3_py_simple_storage % ganache-cli
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:527949)
    at b.set (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:528548)
    at Function.b.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:530917)
    at Function.i.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:526525)
    at new S (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:206543)
    at new p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:195647)
    at new l (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:13485)
    at Object.create (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:94:92509)
    at Object.server (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:38637)
    at Object.<anonymous> (/Users/joe/.config/yarn/global/node_modules/ganache-cli/cli.js:106:22)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by JMiddey** [comment]
The above error was fixed by using node 14 instead of node 17, thanks @davidmurdoch 👍
