### ISSUE TITLE
Can't use ganache-cli because of error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by DieKant** [ConsenSys-archive/ganache#1899]
Hi

I was trying to run a script with ganache-cli (windows 10) and it gave me this error

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at p (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:55:527949)
    at b.set (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:55:528548)
    at Function.i.fromMasterSeed (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:55:526525)
    at new S (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:55:206543)
    at new p (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:55:195647)
    at new l (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:42:13485)
    at Object.create (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:94:92509)
    at Object.server (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\build\ganache-core.node.cli.js:55:38637)
    at Object.<anonymous> (C:\Users\Fedro\AppData\Local\Yarn\Data\global\node_modules\ganache-cli\cli.js:106:22)

It was working fine yesterday, I did not changed/installed anything new in a week so I don't really know why it is behaving like this

Thanks in advance for the advice

**Comment by davidmurdoch** [comment]
Are you using node 12-16?

**Comment by DieKant** [comment]
hi @davidmurdoch 

No, I'm using node version v17.2.0 but from your comment I can immagine the solution been switching version to one that is beetween 12 to 16 right?

EDIT: I found this [repo](https://github.com/coreybutler/nvm-windows) that should do the trick but I didn't understand how to download the installer

**Comment by davidmurdoch** [comment]
`ganache-cli` doesn't support node 17 (they removed core encryption methods it needs). You shouldn't be using node 17 unless you are attempting to prepare your code for the upcoming release of Node 18, or testing Node 17 for Node itself. Node versions are weird.

NVM-windows works well, and I use it myself.

Alternatively, you can use the newest _beta_ of Ganache with Node 17: ganache@7.0.0-beta.2. See installation instructions and known issues here: https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-beta.2

**Comment by DieKant** [comment]
Thanks @davidmurdoch 

I solved the issue by installing the lts 16.13.1 node version form the nvm repo I linked in my last comment
