### ISSUE TITLE
too many forks stay alive

### ISSUE THREAD

**Issue by aymanelya** [ConsenSys-archive/ganache#1928]
So i'm doing some tests regarding calling an async function that forks the mainnet using the ganache npm package in nodejs and executes a transaction,this function is called a couple hundreds of times asynchronously and after awhile my whole computer just freezes.
I wonder at what point the local fork is destroyed (if it is) because i just run 1 transaction and don't need that fork instance to stay alive
Here's how i use it
```js
const Web3 = require('web3');
const Ganache = require("ganache-core");

localWeb3 = new Web3(Ganache.provider({
                  fork: process.env.MAINNET_WS,
                  fork_block_number: "latest",
                  unlocked_accounts: [tx.from],
                  },null,{transactionConfirmationBlocks: 1}))

localWeb3.eth.sendTransaction(tx).then((receipt)=>{console.log(receipt)}).catch(e => {console.log(e)})
```

"ganache-core" version:  2.13.2

**Comment by davidmurdoch** [comment]
Can you try ganache@7.0.0-beta.2? See https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-beta.2 for more information, installation instructions. See the README.md for usage instructions.

**Comment by aymanelya** [comment]
The fork itsef isn't working on the new beta 7.0.0-beta.2

##Code Changes:
```js
const Web3 = require('web3');
const Ganache = require("ganache");

localWeb3 = new Web3(Ganache.provider({
          fork: process.env.MAINNET_WS,
          fork_block_number: "latest",
          },null,{transactionConfirmationBlocks: 1}))
```

```
TypeError: Cannot read properties of undefined (reading 'url')
    at fill (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:214696)
    at /home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:215230
    at Array.forEach (<anonymous>)
    at OptionsConfig.normalize (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:214498)
    at new EthereumProvider (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:124325)
    at new Connector (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:51972)
    at GetConnector (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:210895)
    at Object.initialize (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:198779)
    at Object.provider (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/ganache/dist/node/1.js:2:198241)
    at executeProfit (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/execApi.js:53:36)
    at /home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/execApi.js:40:35
    at Layer.handle [as handle_request] (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/express/lib/router/layer.js:95:5)
    at /home/aymanelya/Documents/projects/BlockchainDev/arbitrage/pancake-biswap/node_modules/express/lib/router/index.js:281:22
```

**Comment by davidmurdoch** [comment]
What is the value of MAINNET_WS? Also, you are passing extra options to Ganache, instead of to Web3.

**Comment by aymanelya** [comment]
just the websocket URL of my bsc node

**Comment by davidmurdoch** [comment]
You can try the following. But I don't think BSC is actually EVM compatible, so you probably won't get the correct results, if the transactions even run at all.

```
// "latest" is the default, so I omitted it
new Web3(Ganache.provider({
          fork: {
            url: process.env.MAINNET_WS
          }
  }) ... web3 options ...);
```

**Comment by davidmurdoch** [comment]
Oh, you may also need to call `await localWeb3.currentProvider.disconnect();` to instruct Ganache to shut everything down each time.

That said, there may be a bug here that prevents Ganache from being automatically garbage collected, which would keep the websocket open forever. You should still use `disconnect` every time anyway, but Ganache does need to at least _try_ to allow the garbage collector to clean up Ganache's hold on the socket connection (if possible, which I'm not sure it even is yet).

**Comment by davidmurdoch** [comment]
@aymanelya any luck?

**Comment by aymanelya** [comment]
I had many issues with the beta version, but i find a better way to do things using eth_call instead of forking mainnet then executing the transactions

**Comment by davidmurdoch** [comment]
Can you let me know what the issues are so I can fix them?

**Comment by cds-amal** [comment]
Closing for issue maintenance. @aymanelya please let us know if you would like this reopened.
