### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'return' of null

### ISSUE THREAD

**Issue by fabianorodrigo** [ConsenSys-archive/ganache#2152]
Hi,

I'm being successful running my tests on ganache v2.5.4 but when I try run them on ganache v7.0.0.
This is my repository: https://github.com/fabianorodrigo/dappsoccerbet

This is the exception I get:
` "before each" hook for "Should Ether goes to ERC20 owner after destroy contract":
     Uncaught TypeError: Cannot read property 'return' of null
      at Object._extract (/home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/packages/contract/lib/reason.js:29:1)
      at /home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/packages/contract/lib/reason.js:64:1
      at /home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (/home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (/home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/home/fabianorodrigo/.nvm/versions/node/v14.16.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)`

Any ideas?

**Comment by davidmurdoch** [comment]
I moved this to truffle, as this is a likely a bug in the way Truffle deals with transaction rejections. Previous issue: https://github.com/trufflesuite/truffle/issues/4639
