### ISSUE TITLE
Zero-pad filter ID

### ISSUE THREAD

**Issue by lukaville** [ConsenSys-archive/ganache#2177]
I'm using web3j library to subscribe to a filter, it doesn't work with ganache but works with geth.

When I create a filter it returns a non-zero padded result.

Actual result:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":73}' http://localhost:8545
{"id":73,"jsonrpc":"2.0","result":"0x1"}
```

Expected result:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":73}' http://localhost:8545
{"id":73,"jsonrpc":"2.0","result":"0x01"}
```

When I specify 0x01 it fails:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x01"],"id":73}' http://localhost:8545
{"id":73,"jsonrpc":"2.0","error":{"message":"filter not found","stack":"Error: filter not found\n    at EthereumApi.eth_getFilterChanges (/opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:20760)\n    at EthereumApi.n.value (/opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:106102)\n    at /opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:237388\n    at RequestCoordinator.<anonymous> (/opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:237216)\n    at /opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:237459\n    at new Promise (<anonymous>)\n    at RequestCoordinator.queue (/opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:237318)\n    at Executor.execute (/opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:232284)\n    at EthereumProvider._requestRaw (/opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:126103)\n    at Connector.<anonymous> (/opt/homebrew/lib/node_modules/ganache/dist/node/1.js:2:52037)","code":-32700}}
```

**Comment by davidmurdoch** [comment]
Per https://eth.wiki/json-rpc/API#eth_newblockfilter, `eth_newBlockFilter` should return a QUANTITY encoded value and `eth_getFilterChanges` should accept a QUANTITY encoded value. `0x01` is actually an invalid QUANTITY value should probably throw a different exception about the received value being invalid.

**Comment by lukaville** [comment]
Yeah, sorry, seems like it is an issue in Web3j: https://github.com/web3j/web3j/issues/1392
