### ISSUE TITLE
Very large eth_debugTrace responses get dropped

### ISSUE THREAD

**Issue by BlinkyStitt** [ConsenSys-archive/ganache#2646]
If I run a forked node and then try to query debug_traceTransaction for [0x2cb2393747247606d0d534950fcbfe2f787161c909c693189c0aed1dacf1f02b](https://etherscan.io/tx/0x2cb2393747247606d0d534950fcbfe2f787161c909c693189c0aed1dacf1f02b), it thinks for a while and then I get back nothing.

```
$ curl --verbose -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "debug_traceTransaction", "params": [ "0x2cb2393747247606d0d534950fcbfe2f787161c909c693189c0aed1dacf1f02b", {  "disableStorage": true } ], "id": 256}' http://localhost:8545
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8545...
* Connected to localhost (127.0.0.1) port 8545 (#0)
> POST / HTTP/1.1
> Host: localhost:8545
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 179
> 
* upload completely sent off: 179 out of 179 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

```
$ ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie --fork https://argobytes:InsecurePasswordCheckedInt
oGit@turbo-eth.stytt.com --chainId 1 --verbose                  
...

Call Gas Limit
==================
9007199254740991

Forked Chain
==================
Location:       https://argobytes:InsecurePasswordCheckedIntoGit@turbo-eth.stytt.com
Block:          14420152
Network ID:     1
Time:           Sat Mar 19 2022 17:49:22 GMT-0700 (Pacific Daylight Time)
Max Cache Size: 1073741824 bytes

Listening on 127.0.0.1:8545

debug_traceTransaction
   > {
   >   "jsonrpc": "2.0",
   >   "method": "debug_traceTransaction",
   >   "params": [
   >     "0x2cb2393747247606d0d534950fcbfe2f787161c909c693189c0aed1dacf1f02b",
   >     {
   >       "disableStorage": true
   >     }
   >   ],
   >   "id": 256
   > }
(node:3676531) UnhandledPromiseRejectionWarning: RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Object.a [as callback] (/home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:14893)
    at /home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:15708
    at /home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:64767
    at /home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:31564
    at p (/home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:31221)
    at /home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:31274
    at t.default (/home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:166358)
    at /home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:32188
    at Object.o [as callback] (/home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:64608)
    at n (/home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:212585)
    at /home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:54514
    at N (/home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:51818)
    at A.w.processBlock (/home/ski/.nvm/versions/node/v12.16.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:51971)
(node:3676531) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 413)
(node:3676531) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

If I send this query to my erigon node, it returns a whopping 987 MB of data.

Hardhat also fails to process this query: https://github.com/NomicFoundation/hardhat/issues/2510

**Comment by BlinkyStitt** [comment]
I'm running ganache v6 above. I'm pretty sure it happens on v7, too. I'll get that installed and confirm though.

**Comment by davidmurdoch** [comment]
v7 can return traces > 10GB, so it shouldn't be a problem, but it is very slow when traces are large (there is a PR to fix it). v6 can't handle large traces. You may need to increase Node.js's max old space size (e.g., `NODE_OPTIONS=--max-old-space-size=16000 ganache`). Let me know if it works.

**Comment by BlinkyStitt** [comment]
I had NODE_OPTIONS set (should have included that in my first post). v7 is printing out lots and lots of logs though. Since v7 works, I think we can close this.

**Comment by BlinkyStitt** [comment]
What is the PR to fix very large traces? I have a bunch of transactions with traces ~1 GB and so would really appreciate that.

**Comment by davidmurdoch** [comment]
The PR actually only speeds up websocket connections: https://github.com/trufflesuite/ganache/pull/2634/files
