### ISSUE TITLE
Uncaught connection exceptions using Ganache as EIP-1193 provider

### ISSUE THREAD

**Issue by mjay0** [ConsenSys-archive/ganache#2879]
First of all, love the project. Thanks for all the great work!

I've written a simple honeypot checking script using Ganache as EIP-1193 provider. However I'm running into a couple of unhandled promise rejection errors when the forking / connecting process fails. The simplest script I can write to trigger the problem is the following:

```
const Ganache = require('ganache')
try {
  const options = { fork: { url: 'https://mainnet.infura.io/v3/INVALID_URL' } }
  Ganache.provider(options)
} catch (e) {
  console.log('something bad occured')
}
```
Ends in:
```
(node:7066) UnhandledPromiseRejectionWarning: Error: Invalid JSON response from fork provider:

 invalid project id


The provided fork url, https://mainnet.infura.io/v3/INVALID_URL, may be an invalid or incorrect Infura endpoint.
Visit https://infura.io/docs/ethereum for Infura documentation.
    at /mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:83425
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7066) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7066) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Other errors I'm not able to catch in production (on connection):

```
(node:7466) UnhandledPromiseRejectionWarning: Error: could not find results for height #xxxxxxx
    at /mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:80254
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async HttpHandler.queueRequest (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:80407)
    at async HttpHandler.request (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:82486)
    at async getBlockByNumber (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:88979)
    at async resolveTargetAndClosestAncestor (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:89982)
    at async PersistentCache.initialize (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:93130)
    at async Fork.initCache (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:76756)
    at async Fork.initialize (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:76713)
    at async Blockchain.initialize (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:43422)
    at async EthereumProvider.initialize (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:126794)
    at async Connector.connect (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:53185)
```

(not sure why I'm getting a transaction signature as I'm only connecting and not submitting anything)
```
(node:7033) UnhandledPromiseRejectionWarning: Error: Transaction signature is incomplete; v, r, and s are required.
    at EIP2930AccessListTransaction.RuntimeTransaction.validateAndSetSignature (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:174704)
    at new EIP2930AccessListTransaction (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:167130)
    at Function.fromTxData (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:167626)
    at Function._fromData (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:180835)
    at Function.fromRpc (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:181402)
    at /mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:59048
    at Array.forEach (<anonymous>)
    at Function.rawFromJSON (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:58849)
    at Fork.initialize (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:76690)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Blockchain.initialize (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:43422)
    at async EthereumProvider.initialize (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:126794)
    at async Connector.connect (/mnt/c/Users/User/Desktop/Ganache-test/node_modules/ganache/dist/node/1.js:2:53185)
```

Both are occurring randomly when using a Cronos RPC. They are likely caused by an issue with the RPC itself but would be great I was able to catch these for some better error handling.

**Comment by davidmurdoch** [comment]
Are you using a local build or a published build (from npm or Docker)? If a published build, what version?

**Comment by mjay0** [comment]
Apologies, that should have been included. I'm running latest version on npm:

```
$ npm view ganache version
7.0.4
$ node -v
v17.9.0
```

**Comment by davidmurdoch** [comment]
Thanks,

Looks like we need to surface a way for callers to handle errors thrown by the background promise. The only way to do it right now is listen for an unhandled promise rejection:

```javascript
// Example:
process.on('unhandledRejection', function(reason, p){
    console.log("Possibly Unhandled Rejection at: Promise ", p, " reason: ", reason);
});
```

The last one error is very interesting. Do you know what Cronos block number were you connecting at?

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.
