### ISSUE TITLE
Forking Arbitrum Nitro chains gives "Invalid transaction type"

### ISSUE THREAD

**Issue by jaketimothy** [ConsenSys-archive/ganache#3458]
Running `ganache --fork <url>` with an Arbitrum Nitro network returns `Error: Invalid transaction type: 106`.  I have attempted with Alchemy and QuickNode endpoints, and tried both Arbitrum Rinkeby and Arbitrum Goerli.

```console
ganache v7.4.0 (@ganache/cli: 0.5.0, @ganache/core: 0.5.0)
Starting RPC server
Error: Invalid transaction type: 106
    at Function.typeOf ([myproject]/node_modules/ganache/dist/node/1.js:2:218592)
    at Function.typeOfRPC ([myproject]/node_modules/ganache/dist/node/1.js:2:218818)
    at Function.fromRpc ([myproject]/node_modules/ganache/dist/node/1.js:2:217517)
    at [myproject]/node_modules/ganache/dist/node/1.js:2:90737
    at Array.forEach (<anonymous>)
    at Function.rawFromJSON ([myproject]/node_modules/ganache/dist/node/1.js:2:90566)
    at Fork.initialize ([myproject]/node_modules/ganache/dist/node/1.js:2:108321)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Blockchain.initialize ([myproject]/node_modules/ganache/dist/node/1.js:2:74897)
    at async EthereumProvider.initialize ([myproject]/node_modules/ganache/dist/node/1.js:2:161074)
```

**Comment by jaketimothy** [comment]
Alchemy RPC request to arbgoerli:
`{ "jsonrpc": "2.0", "id": 2, "method": "eth_getBlockByNumber", "params": ["latest", true] }`

Response (note `"type": "0x6a"`):
```
{
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "number": "0x168d1",
    "baseFeePerGas": "0x5f5e100",
    "difficulty": "0x1",
    "extraData": "0x37c327c5d25cce0204b31cdebc4e8a7c2756f3aaa3067f4e9808c3c92b41addd",
    "gasLimit": "0x4000000000000",
    "gasUsed": "0xc2a3",
    "hash": "0x43ef03219442dd2a1cffb96c29f58c8fe58fe1d474eb0848319f25176a5938da",
    "l1BlockNumber": "0x70a6c8",
    "logsBloom": "0x00000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "0xa4b000000000000000000073657175656e636572",
    "mixHash": "0x00000000000009c9000000000070a6c800000000000000040000000000000000",
    "nonce": "0x0000000000000bf1",
    "parentHash": "0x5f8a33312928268af8f0cc8d111dba6b9bfc40c306adf8e7e7541378a8413399",
    "receiptsRoot": "0x3ab692fbdbe491c378ab09d9a794c3f1ccf3e83d9b6b2df604435fa47faa5e92",
    "sendCount": "0x9c9",
    "sendRoot": "0x37c327c5d25cce0204b31cdebc4e8a7c2756f3aaa3067f4e9808c3c92b41addd",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0x3eb",
    "stateRoot": "0xbdfe51994fc84a3bd45a3155a608207bf6388d3d8d29d9c86c2ffffe6625dc26",
    "timestamp": "0x62f459d1",
    "totalDifficulty": "0x168d2",
    "transactions": [
      {
        "hash": "0x3c2392318ec2e47771e61341262f3dd893edc74ee7592488a993ec093318ebe1",
        "blockHash": "0x43ef03219442dd2a1cffb96c29f58c8fe58fe1d474eb0848319f25176a5938da",
        "blockNumber": "0x168d1",
        "chainId": "0x66eed",
        "from": "0x00000000000000000000000000000000000a4b05",
        "gas": "0x0",
        "gasPrice": "0x0",
        "input": "0x6bf6a42d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070a6c700000000000000000000000000000000000000000000000000000000000168d1000000000000000000000000000000000000000000000000000000000000004b",
        "nonce": "0x0",
        "r": "0x0",
        "s": "0x0",
        "to": "0x00000000000000000000000000000000000a4b05",
        "transactionIndex": "0x0",
        "type": "0x6a",
        "v": "0x0",
        "value": "0x0"
      },
      {
        "hash": "0xe524908ed00ced56da8c074752ab975beca532d137c6231b7a0d404ccd5ec64a",
        "blockHash": "0x43ef03219442dd2a1cffb96c29f58c8fe58fe1d474eb0848319f25176a5938da",
        "blockNumber": "0x168d1",
        "from": "0x2ac9f267cc85ab2356db6e1df2b8813fe98b96ee",
        "gas": "0xd7a9",
        "gasPrice": "0x5f5e100",
        "input": "0xeaf5d04e0000000000000000000000002ac9f267cc85ab2356db6e1df2b8813fe98b96ee00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002f757064617465204865616c7468626f745f3432313631335f312073657420636f756e7465723d636f756e7465722b310000000000000000000000000000000000",
        "nonce": "0x343",
        "r": "0x5392bb8c8ab2e632701ff1963f8f2b3ffd87d408f5d8dc5e0757ea7b1306ddd0",
        "s": "0x3587914fd961e57cf69a8c400d2d0586bf4519e447162758750dfc0a4b175721",
        "to": "0x033f69e8d119205089ab15d340f5b797732f646b",
        "transactionIndex": "0x1",
        "type": "0x0",
        "v": "0xcddfd",
        "value": "0x0"
      }
    ],
    "transactionsRoot": "0x63e5e416ad7f69d2aa9723b638de22f9becabbbd258feef0f792f6dad09dbff7",
    "uncles": []
  }
}
```
