### ISSUE TITLE
Coded error: Invalid Request in ganache v7.4.3

### ISSUE THREAD

**Issue by AoDev** [ConsenSys-archive/ganache#3633]
I'm getting this error when trying to launch ganache and forking Arbitrum 

Command

```
ganache --chain.chainId 42161 --chain.vmErrorsOnRPCResponse true --wallet.totalAccounts 10 --fork.url https://arb-mainnet.g.alchemy.com/v2/EDITED --miner.blockGasLimit 120000000 --wallet.mnemonic brownie --server.port 8548
```

```
ganache v7.4.3 (@ganache/cli: 0.5.3, @ganache/core: 0.5.3)
Starting RPC server
eth_blockNumber
CodedError: invalid request
    at /Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:112108
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HttpHandler.queueRequest (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:112261)
    at async HttpHandler.request (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:114428)
    at async getBlockByNumber (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:120586)
    at async resolveTargetAndClosestAncestor (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:121589)
    at async PersistentCache.initialize (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:124853)
    at async Fork.initCache (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:108610)
    at async Fork.initialize (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:108567)
    at async Blockchain.initialize (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:74966) {
  code: -32600
}
```

**Comment by ethangao** [comment]
Same error to me on ethereum mainnet.
From alchemy dashboard, seems like ganache is passing params {block:earliest} to call eth_blockNumber.

➜  ~ ganache --fork https://eth-mainnet.g.alchemy.com/v2/KEY@15485091  --chain.chainId 1 --networkId 1
ganache v7.4.3 (@ganache/cli: 0.5.3, @ganache/core: 0.5.3)
Starting RPC server
CodedError: invalid request
    at /usr/local/lib/node_modules/ganache/dist/node/1.js:2:112108
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HttpHandler.queueRequest (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:112261)
    at async HttpHandler.request (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:114428)
    at async getBlockByNumber (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:120586)
    at async resolveTargetAndClosestAncestor (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:121589)
    at async PersistentCache.initialize (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:124853)
    at async Fork.initCache (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:108610)
    at async Fork.initialize (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:108567)
    at async Blockchain.initialize (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:74966) {
  code: -32600
}

**Comment by damn1** [comment]
Same here on forking eth mainnet, since a few hours. Yesterday no problems with same setup.

**Comment by dezzeus** [comment]
Same issue (and same – Alchemy – provider); the block number is reported when forking.

FYI, a colleague of mine with an already forked network got the error on web3_clientVersion:

> ganache v7.0.3 (@ganache/cli: 0.1.4, @ganache/core: 0.1.4)
Starting RPC server
web3_clientVersion
CodedError: invalid request
    at /usr/local/lib/node_modules/ganache/dist/node/1.js:2:80254
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async HttpHandler.queueRequest (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:80407)
    at async HttpHandler.request (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:82486)
    at async getBlockByNumber (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:88979)
    at async resolveTargetAndClosestAncestor (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:89982)
    at async PersistentCache.initialize (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:93130)
    at async Fork.initCache (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:76756)
    at async Fork.initialize (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:76713)
    at async Blockchain.initialize (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:43422) {
  code: -32600
}

**Comment by davidmurdoch** [comment]
It looks like Alchemy has stopped responding to the "earliest" block tag which Ganache fetches on startup. I'll try to get in touch with someone from alchemy today to see if they can fix this. Thank you for all of the reports.

**Comment by davidmurdoch** [comment]
I've confirmed this is a new bug in Alchemy introduced sometime within the past 24 hours. I haven't been able to get a hold of anyone at Alchemy yet; if anyone here knows someone at Alchemy please send them the link to this issue!

In the meantime you can use ganache's built-in forking nodes for mainnet, ropsten, kovan, rinkeby, goerli (görli), and sepolia via `ganache --fork <network name>`; ganache's built-in nodes provide free archive support and a _very_ high per-IP rate limit. For other chains, like Arbitrum, Optimism, etc, you can sign up for an [Infura](https://infura.io) account and use an Infura node URL instead of your alchemy node URL, e.g., `ganache --fork.url <URL>`.

**Comment by AoDev** [comment]
Someone from alchemy has been answering and provided this [example](https://composer.alchemy.com?share=eJyVl09P4zAQxb9Lzhx2l1tvbaUuSCxUwHJBCE3TaRvh2JHtUCrEd187aYszHrvdC6Lz3u.Zjv.E_SzKDVSyGP28KCTardJvxejXD.erRrtRy1uosRgV7v.XNdqJUOXbZHfb1gvUxcFz19hKSVOMnj_LdxCtB0CUG6x3Hhobg.ZRgzQr1MZRAhYosp6vCzbpUb2hHAuhtiBL5JOIJ5c0AeE9iS4NLbmcP2hhCRYyOUdLKscPHUr.HO_xxKqxqV4xxjBzoXT3PFs3MX6GDhHDOkNMW61R2rlWjTLd5BKUGtIZTyAqN1g1mOykhcm5V8pegdnE_FFhqIdqLd3iGSfQoRzyfnFDWapWDp76oEz9C78TjvsgREKFUiUIQexdKfL5PXm9pNZ9lbrR2KoGi7_Bdj9UKLVCvKqMm4IdgQKBMmswc10Ntt6gHPndkdHvIEp8CxzTHzNkHhkxzbJTE8kpntmDrJzig1069esnO5aE_fzs7FiTdiZ.qpbMRHVVxj2rhEU93YBcD85QVk7yN2qdhDuNIXkm5XYnllrF9r7M_JnThyoM9eA2DKxxbGPsW2K4YH4mu27GfAtjubyWS.yIw074z2qhXwH.0wYhTrXCP77Yks.p1ms2pnfkU.abNZtz8JyVZPbP5JzEo5dJ.itLgWfNedJ5IvXUPGe8qeT9GXLsSiI0sp2TlzrHUkaaWcOHew0pXdndDHGOOn4hshaaI3HbNdMfQiSBiAybwtLEHOWykutg_aQykk6a2mhlVanEk7vyOBdJoiqljWvmHrZBMySAMUQZO1m6rlJwX6XuVlbSWHcXYkdO1ZDu3lDSatcN5iLOqYSeCaU0vdYM64S4Ae3eaXYc3xkZkbC3s0e_m6EQM6SRrsK4ZkpPlRBI54yVCX_39ffjTAJnSGV0Xz0JvNcI_dBAfZgpMtihFHKVCbWAIkLIuK.cV_Hut_jWVLg6h3VKvEf7KKyG7gb86ZK7SqYcYYpG1wu3jJixRVLI_Qr23yABElZjN.kqCYqxV6dOBVZmeGwE9Kd4YAyfTt6XSsx2KnLEKe5vkg_1kNzi4vK1FJX.no2WByNGrNnAJUW62tfLhV8lULvv5NbdnkfPBYJ2YcYthBUIgy9f.wBbZWB9), which is working.

Pending more investigation.

**Comment by davidmurdoch** [comment]
Looks like this has been fixed on Alchemy's end: `curl -X POST --data '{"jsonrpc":"2.0","method": "eth_getBlockByNumber", "params": ["earliest", false], "id": 1}' https://eth-mainnet.g.alchemy.com/v2/<KEY HERE>` now works! @AoDev, are you able to confirm?

**Comment by AoDev** [comment]
@davidmurdoch Yes I just tried, I forked Arbitrum using Alchemy. It worked and I connected Brownie to it. 

Looks good : )
