### ISSUE TITLE
fail to install and run ganache 

### ISSUE THREAD

**Issue by vanilingys99** [ConsenSys-archive/ganache#3661]
When **npm install ganache --global**

```
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     undefined,
npm WARN cleanup     AssertionError [ERR_ASSERTION]: rimraf: missing path
npm WARN cleanup         at rimraf (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:54:3)
npm WARN cleanup         at node:internal/util:360:7
npm WARN cleanup         at new Promise (<anonymous>)
npm WARN cleanup         at rimraf (node:internal/util:346:12)
npm WARN cleanup         at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:528:20
npm WARN cleanup         at Array.map (<anonymous>)
npm WARN cleanup         at Arborist.[rollbackCreateSparseTree] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:528:8)
npm WARN cleanup         at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1074:50
npm WARN cleanup         at async Arborist.[reifyPackages] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:231:11)
npm WARN cleanup         at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:151:5) {
npm WARN cleanup       generatedMessage: false,
npm WARN cleanup       code: 'ERR_ASSERTION',
npm WARN cleanup       actual: undefined,
npm WARN cleanup       expected: true,
npm WARN cleanup       operator: '=='
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\vanyk\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\bufferutil',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\vanyk\AppData\Roaming\npm\node_modules\ganache\node_modules\bufferutil'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\vanyk\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\bufferutil'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\vanyk\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\utf-8-validate',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\vanyk\AppData\Roaming\npm\node_modules\ganache\node_modules\utf-8-validate'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\vanyk\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\utf-8-validate'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\vanyk\AppData\Roaming\npm\node_modules\ganache\node_modules\leveldown
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! 'node-gyp-build' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vanyk\AppData\Local\npm-cache\_logs\2022-09-15T12_55_52_877Z-debug.log
```

**Comment by davidmurdoch** [comment]
Can you provide more information about your system? Os, node version, npm version, etc?

**Comment by AngelPn** [comment]
I'm having the same issue. Here are some of my system informations.
OS: Windows 10
node: v16.13.0
npm: 8.1.0

**Comment by davidmurdoch** [comment]
@AngelPn can you paste the output of `npm install ganache@latest -g`?

**Comment by AngelPn** [comment]
@davidmurdoch Here is the output:
```
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ap\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\bufferutil',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ap\AppData\Roaming\npm\node_modules\ganache\node_modules\bufferutil'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ap\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\bufferutil'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ap\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\utf-8-validate',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ap\AppData\Roaming\npm\node_modules\ganache\node_modules\utf-8-validate'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ap\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\utf-8-validate'npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\ap\AppData\Roaming\npm\node_modules\ganache\node_modules\leveldown
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! 'node-gyp-build' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ap\AppData\Local\npm-cache\_logs\2022-10-18T15_16_40_205Z-debug.log
```

**Comment by cds-amal** [comment]
Hi @AngelPn,

I was able to install Ganache without issues on Windows 10 (`Node v16.18.0`, `npm v8.19.2`). Can you try with latest Node v16?

**Comment by oporko** [comment]
Having the same issue, although mine fails later because I don't have Visual Studio installed.

```
C:\Windows\system32>npm -g install ganache@latest
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\bufferutil',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\User\AppData\Roaming\npm\node_modules\ganache\node_modules\bufferutil'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\bufferutil'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\utf-8-validate',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\User\AppData\Roaming\npm\node_modules\ganache\node_modules\utf-8-validate'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\utf-8-validate'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ganache',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\User\AppData\Roaming\npm\node_modules\ganache\node_modules\bufferutil'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ganache\\node_modules\\bufferutil'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\User\AppData\Roaming\npm\node_modules\ganache\node_modules\leveldown
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.0 found at "C:\Python311\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
npm ERR! gyp ERR! stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7npm ERR! gyp ERR! stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\User\AppData\Roaming\npm\node_modules\ganache\node_modules\leveldown
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2022-12-15T20_58_16_604Z-debug-0.log
```

OS: Windows 10 22H2
Node: 18.12.1
npm: 9.20

I've been using 7.5.0 without issue, this occurred when upgrading to 7.7.0.  I removed 7.5.0 and tried installing latest with same result.

**Comment by davidmurdoch** [comment]
@oporko Hm, this shouldn't be happening. As a workaround can you try reinstall Node v18 via the [official Node installer](https://nodejs.org/en/download/), and during the installation make sure you also install the build tools? Unless you are sure you already did that the first time you installed it.

**Comment by davidmurdoch** [comment]
@oporko this should be checked:

![image](https://user-images.githubusercontent.com/187813/207983719-34dd6ba9-c792-4881-8069-d13f3158aaf9.png)

**Comment by davidmurdoch** [comment]
@oporko if you haven't yet reinstalled Node.js to include the build tools, can you try installing the latest version of Ganache? It should fix the issue for you. Run: `npm install ganache@latest --global`
