### ISSUE TITLE
fail to install ganache in Mac

### ISSUE THREAD

**Issue by michaelclubman515** [ConsenSys-archive/ganache#3697]
Hi there：
I failed to install ganache in terminal ,could you  please help to give some idea to fix this,thanks !

Mac mini(M1 2020) ,macOS Monterey
Node.js V18.9.0

/**(base) liwei@liweideMac-mini-2 npm % ganache-cli -g
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Yargs (/Users/liwei/.config/yarn/global/node_modules/ganache-cli/node_modules/yargs/yargs.js:38:27)
    at Argv (/Users/liwei/.config/yarn/global/node_modules/ganache-cli/node_modules/yargs/index.js:12:16)
    at Object.<anonymous> (/Users/liwei/.config/yarn/global/node_modules/ganache-cli/node_modules/yargs/index.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
**/

**Comment by davidmurdoch** [comment]
`ganache-cli` is now `ganache`. Try `npm uninstall ganache-cli -g && npm install ganache -g`
