### ISSUE TITLE
0 should be a supported port

### ISSUE THREAD

**Issue by sewinter** [ConsenSys-archive/ganache#3805]
1. 0 should be a supported port.
2. Yikes to this error message:

```
Error: Port should be >= 0 and < 65536. Received 0.
    at Server.listen (webpack://Ganache/../core/lib/src/server.js:157:25)
    at ForkManager.createNewServer (/Users/samuelwinter/src/backrun/src/fork/ForkManager.ts:60:12)
    at ForkManager.simulateTx (/Users/samuelwinter/src/backrun/src/fork/ForkManager.ts:26:35)
    at handleMempoolTx (/Users/samuelwinter/src/backrun/src/backrun/mempool.ts:54:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by davidmurdoch** [comment]
Hey, can you provide reproduction steps? Also, what version are you using?

**Comment by sewinter** [comment]
Hi David, I'm on `7.4.4`. Repro:

```
 const server = ganache.server({
      fork: {
        url: FORK_URL,
      },
      server: {
        ws: true,
      },
    });
    server.listen(0);
```

**Comment by davidmurdoch** [comment]
Looks like a duplicate of https://github.com/trufflesuite/ganache/issues/2643. I'll try to get the priority bumped up on this for you. I suspect it will be an easy fix. Thanks for reporting!

**Comment by sewinter** [comment]
Thank you! I ended up writing a utility to find a free port, so it's not super urgent for me.
