### ISSUE TITLE
Cannot read properties of undefined (reading 'toggleStepEvent')

### ISSUE THREAD

**Issue by tobiaskemkes** [ConsenSys-archive/ganache#3921]
Hey there,

I’m following the documentation of the Ganache npm package: https://www.npmjs.com/package/ganache.
I use version 7.5.0 of the npm package and ganache as an EIP-1193 provider only.
I run into an error with the ganache:vm:tx:step provider event, all other provider events seem to work fine.
Please see the Typescript code snippet and the error below.

Any help would be much appreciated!

**Code Snippet:**
```
const ganache = require("ganache");

const options = {};

const provider = ganache.provider(options);

const contexts = new Map();
provider.on("message", (event: any) => {
  console.log(event);
});
provider.on("ganache:vm:tx:before", (event: any) => {
  console.log(1);
  contexts.set(event.context, []);
});
provider.on("ganache:vm:tx:step", (event: any) => {
  console.log(2);
  contexts.get(event.context).push(event.data);
});
provider.on("ganache:vm:tx:after", (event: any) => {
  console.log(3);
  console.log(contexts.get(event.context));
  contexts.delete(event.context);
});
```
**Error:**

```
webpack://Ganache/../../chains/ethereum/ethereum/lib/src/blockchain.js:1184        __classPrivateFieldGet(this, _Blockchain_miner, "f").toggleStepEvent(enable);

TypeError: Cannot read properties of undefined (reading 'toggleStepEvent') at Blockchain.toggleStepEvent (webpack://Ganache/../../chains/ethereum/ethereum/lib/src/blockchain.js:1184:57) at onChange (webpack://Ganache/../../chains/ethereum/ethereum/lib/src/provider.js:203:24) at webpack://Ganache/../../chains/ethereum/ethereum/lib/src/provider.js:58:17 at /Users/x/Development/xrpc/node_modules/ganache/node_modules/emittery/index.js:306:13 at Array.map (<anonymous>) at EthereumProvider.emit (/Users/x/Development/xrpc/node_modules/ganache/node_modules/emittery/index.js:304:23)
```

**Comment by davidmurdoch** [comment]
Thanks for opening this. This is a bug!

You can work around this by changing your code to:

```
const ganache = require("ganache");

const options = {};

const provider = ganache.provider(options);

// wait until provider has finished setting up its internals before subscribing to events
provider.on("connect", () => {
  const contexts = new Map();
  provider.on("message", (event: any) => {
    console.log(event);
  });
  provider.on("ganache:vm:tx:before", (event: any) => {
    console.log(1);
    contexts.set(event.context, []);
  });
  provider.on("ganache:vm:tx:step", (event: any) => {
    console.log(2);
    contexts.get(event.context).push(event.data);
  });
  provider.on("ganache:vm:tx:after", (event: any) => {
    console.log(3);
    console.log(contexts.get(event.context));
    contexts.delete(event.context);
  });
});
```

**Comment by davidmurdoch** [comment]
Some backstory: the data that makes up a `"step"` event is expensive to create so we only create it if there is a listener. Some of our internals take a small amount of time to initialize, so when you subscribed to `"ganache:vm:tx:step"` the `provider` tried to tell this internal that it should create and emit step events.... but that internal doesn't exist yet.

Sorry about this! We'll fix it soon so you don't have to wait to subscribe to these events.

**Comment by tobiaskemkes** [comment]
Thank you for the quick response and clarification, it works now!
