### ISSUE TITLE
Invalid `hardfork` throws unrelated error 

### ISSUE THREAD

**Issue by jeffsmale90** [ConsenSys-archive/ganache#4181]
If an invalid value is provided as `chain.hardfork` (in programmatic usage), an unhelpful error is raised:

```
const server = ganache.server({ chain: { hardfork: "not-a-hardfork" } };
```

Will result in:
```
events.js:377
      throw er; // Unhandled 'error' event
      ^
Error [OpenError]: Parent database is not open
    at /Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:180046
    at /Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:1369681
    at onopen (/Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:1378217)
    at /Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:1369681
    at /Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:1369681
    at onopen (/Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:1367599)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event on LevelUP instance at:
    at /Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:179094
    at /Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:180044
    at /Users/jeffsmale/repro/node_modules/ganache/dist/node/0.js:2:1369681
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by cliffoo** [comment]
Yes the cli error is much clearer.

```sh
$ ganache -k not-valid
Invalid values:
  Argument: chain.hardfork, Given: "not-valid", Choices: "constantinople", "byzantium", "petersburg", "istanbul", "muirGlacier", "berlin", "london", "arrowGlacier", "grayGlacier"
```
