### ISSUE TITLE
Decoding Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by Dalois-30** [ConsenSys-archive/ganache#4295]
PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1677$ of contract$ ChainAsset (ID 2918)
    at /tmp/.mount_ganach5sx6lb/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/tmp/.mount_ganach5sx6lb/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/tmp/.mount_ganach5sx6lb/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_ganach5sx6lb/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_ganach5sx6lb/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jeffsmale90** [comment]
Thanks for raising this issue @Dalois-30. We have just released a new version of Ganache UI which fixes a bunch of issues! Can you please download v2.7.0 https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.0 and see if this fixes the issue?

If it's still a problem, can you please raise the issue in the new Ganache UI project https://github.com/trufflesuite/ganache-ui?
