### ISSUE TITLE
console ganache error

### ISSUE THREAD

**Issue by hbarrabasqui** [ConsenSys-archive/ganache#4365]
I have a problem with using ganache in console. When I want to run Ganache it generates thousands of lines of data and ends with this:
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/mnt/c/Users/Pampa/AppData/Roaming/npm/node_modules/ganache/dist/node/cli.js:2:21839)
    at /mnt/c/Users/Pampa/AppData/Roaming/npm/node_modules/ganache/dist/node/cli.js:2:21160
    at Array.reduce (<anonymous>)
horacio@DESKTOP-DJSHN39:~/demos/web3_py_simple_storage$

**Comment by jeffsmale90** [comment]
Can you please confirm the version of nodejs and the version of ganache that you have installed?

Thanks!

**Comment by hbarrabasqui** [comment]
Hi, @jeffsmale90 , Sorry for the delay in responding. Install nodejs again and it worked. I don't know exactly what was going on but that problem has been fixed. Now I have another problem, but it is when I want to verify a smart contract, but I already made the query.
Thanks for your time.
