### ISSUE TITLE
Start ganache error

### ISSUE THREAD

**Issue by zondixji** [ConsenSys-archive/ganache#4451]
I have a problem with using ganache in console. When I want to run Ganache it generates thousands of lines of data and ends with this:

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/usr/local/lib/node_modules/ganache/dist/node/cli.js:2:21839)
    at /usr/local/lib/node_modules/ganache/dist/node/cli.js:2:21160
    at Array.reduce (<anonymous>)

my nodejs version is v12.22.9

Thanks

**Comment by davidmurdoch** [comment]
v12 isn't supported. Use versions v14-18

**Comment by zondixji** [comment]
Thanks
