### ISSUE TITLE
eth_getTransactionByHash failing with "Error: Number can only safely store up to 53 bits" when using ganache-cli with fork

### ISSUE THREAD

**Issue by acryptosx** [ConsenSys-archive/ganache#961]
This works fine when connected directly to the un-forked node, but when connected to the local forked ganache-cli node, trying to get a transaction results in:

truffle(bscforktest)> web3.eth.getTransaction('0x023d62577aab3260d6328838ef332216286495b171494b798c74fc7818a94e58')
Uncaught Error: Returned error: Number can only safely store up to 53 bits
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:554:1)
    at WebSocketConnection.EventEmitter.emit (domain.js:486:12)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:205:1)
    at W3CWebSocket.onMessage (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:234:1)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/yaeti/lib/EventTarget.js:115:1)
    at WebsocketProvider._onMessage (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:118:1)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:133:1
    at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:170:1
    at Object.ErrorResponse (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/errors.js:29:1)

ganache-cli is started with:
ganache-cli --fork wss://bsc-ws-node.nariox.org:443

Version: Ganache CLI v6.12.2 (ganache-core: 2.13.2)

**Comment by davidmurdoch** [comment]
Closing as this issue should now be fixed in ganache@7.0.0-alpha.0. Please comment below if you are still seeing this issue in the latest ganache.
