### ISSUE TITLE
ganache-cli failing to eth_estimateGas

### ISSUE THREAD

**Issue by RomanHiden** [ConsenSys-archive/ganache#962]
running fork with the following command

```
ganache-cli --accounts 10 --hardfork istanbul --fork https://eth-mainnet.alchemyapi.io/v2/KEY --gasLimit 12000000 --mnemonic brownie --port 5458 --chainId 1 -h 0.0.0.0 \
    -u 0xB7F72028D9b502Dc871C444363a7aC5A52546608\
    -u 0xb72b31907c1c95f3650b64b2469e08edacee5e8f\
    -u 0x56d811088235F11C8920698a204A5010a788f4b3\
    -u 0x18240BD9C07fA6156Ce3F3f61921cC82b2619157\
    -u 0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7\
    -u 0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490\
    -u 0xe26A220a341EAca116bDa64cF9D5638A935ae629\
    -u 0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8\
    -u 0x95beec2457838108089fcd0e059659a4e60b091a\
    -u 0x9B5dFE7965C4A30eAB764ff7abf81b3fa96847Fe\
    -u 0xfe36046f6193d691f99e2c90153003f8938cfc41\
    -u 0xF69D58D756f2c9b2D37fB50a62736E92253F1c7f\
    -u 0x42a3FDad947807f9FA84B8c869680A3B7A46bEe7\
    -u 0xddAd23Dd65ac23f3e6b4E2706575A90D50349Eb3

```

for some transaction metamask failing to estimate gas. this is server logs of the failure

```
eth_estimateGas
   > {
   >   "id": 1309872693,
   >   "jsonrpc": "2.0",
   >   "method": "eth_estimateGas",
   >   "params": [
   >     {
   >       "to": "0xe7ed6747fac5360f88a2efc03e00d25789f69291",
   >       "gas": "0x7a120",
   >       "data": "0xcf86add5000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000400000000000000000000000056d811088235f11c8920698a204a5010a788f4b3000000000000000000000000b72b31907c1c95f3650b64b2469e08edacee5e8f00000000000000000000000018240bd9c07fa6156ce3f3f61921cc82b2619157000000000000000000000000e26a220a341eaca116bda64cf9d5638a935ae6290000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003635c9adc5dea0000000000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000056bc75e2d63100000",
   >       "from": "0xf69d58d756f2c9b2d37fb50a62736e92253f1c7f"
   >     }
   >   ]
   > }
 <   {
 <     "id": 1309872693,
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "message": "VM Exception while processing transaction: revert",
 <       "code": -32000,
 <       "data": {
 <         "stack": "c: VM Exception while processing transaction: revert\n    at Function.c.fromResults (/home/roman/.nvm/versions/node/v10.22.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\n    at e.exports (/home/roman/.nvm/versions/node/v10.22.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2089395)",
 <         "name": "c"
 <       }
 <     }
 <   }

```

## Your Environment
* Version used: Ganache CLI v6.12.2 (ganache-core: 2.13.2)
* Version of Truffle/Remix/Other tools used: brownie version 1.13.0
* NodeJS Version: v10.22.0
* Operating System and version (include distro if Linux): aws amazon linux
* Link to your project or repro gist: https://github.com/bZxNetwork/contractsV2

**Comment by DenrianWeiss** [comment]
It seems that at [gas-estimator.ts](https://github.com/trufflesuite/ganache/blob/develop/src/chains/ethereum/ethereum/src/helpers/gas-estimator.ts), the functions return any error that it receive, but in the [@ethereumjs/vm impl](https://github.com/ethereumjs/ethereumjs-monorepo/blob/f15f28b580923d040c6bdf9de68ff38cf1f5fab4/packages/vm/src/evm/interpreter.ts#L116), the ERROR.REVERT will return after step hook is executed, so the finally result of api will be the VM exception. Maybe the exception should be handled?

**Comment by bakeiro** [comment]
I agree with this issue, I execute the estimateGas in the rinkeby network, and the promise works with problems, when I change to ganache blockchain, it fails (catch method of the JS promise is executed), and I get the same error code

**Comment by davidmurdoch** [comment]
Can you try ganache@7.0.0-beta.2? https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-beta.2

**Comment by cprates** [comment]
Same problem here. Bumping version to v7.4.0 solved the problem

**Comment by kraymond37** [comment]
The problem still exists.

**Comment by jeffsmale90** [comment]
@kraymond37 do you have a reproduction? Thanks.
